# Dockerfile.buffer
FROM python:3.11-slim

RUN apt-get update && apt-get install -y git curl \
    && rm -rf /var/lib/apt/lists/*

# Clone repo
WORKDIR /app
RUN git clone https://github.com/luckyduckcode/lightning-buffer.git .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
COPY .env.buffer .env
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]